### ISSUE TITLE
Server side encryption

### ISSUE THREAD

**Issue by LostInCompilation** [e-alfred/flowupload#348] opened 2021-05-02 00:58 UTC
I just read that server side encryption is not supported. However I had running this app for month using legacy server side encryption and it worked perfectly fine.
Is this behavior expected? Maybe the App supports encryption now and this is just an old message.

Currently I cannot test this App any further, because it is incompatible with Nextcloud21.

**Comment by JonathanTreffler** [comment] 2021-06-25 15:46
To be honest I have no idea if our app is working with encryption :rofl: 
 There is no specific reason why it shouldn't, but we have never tested/validated it.
 Many other apps don't support encryption, so I assumed it would be hard to implement.
 
 It is also possible, that flowupload works with encryption enabled, but doesn't actually store the files encrypted.

**Comment by JonathanTreffler** [comment] 2021-07-11 11:56
duplicate of #3

**Closed by JonathanTreffler** 2021-07-11 11:56 UTC
