### ISSUE TITLE
Initial letter

### ISSUE THREAD

**Issue by raudraido** [e-alfred/flowupload#15] opened 2018-02-15 15:51 UTC
Hi,

In Estonain language we have letters ÄÖÜÕ.. Flowupload won´t upload file if its name contains big ÕÄÖÜ letters.

**Comment by e-alfred** [comment] 2018-03-05 12:03
This is a duplicate of https://github.com/e-alfred/flowupload/issues/7. Please add your issue there.

**Closed by e-alfred** 2018-03-05 12:03 UTC
Labels: bug
