### ISSUE TITLE
Feature request : Choose destination folder

### ISSUE THREAD

**Issue by ischiros** [e-alfred/flowupload#79] opened 2020-04-09 10:09 UTC
Hello,

It would be great to allow user to choose a destination folder, instead of uploading to their personnal folder.
We use GroupFolder, with a folder containing the photos of our events. Photographs need to upload large numbers of files there. Today, they have the choicie between uploading in their personnal folder and then moving to the good folder, or zipping, uploading, unzipping. Moving the files directly to the good folder would be a useful improvement.

Thanks for everyone's work :)

**Comment by TessyPowder** [comment] 2020-04-09 10:30
Duplicate of #4 
I am currently developing this feature: #73

**Closed** 2020-04-09 11:27 UTC
Labels: duplicate
