### ISSUE TITLE
Failing to upload some charaters

### ISSUE THREAD

**Issue by PenguinFreeDom** [e-alfred/flowupload#16] opened 2018-02-27 10:17 UTC
Hi.
I cant upload filenames with non english charaters like "æøå"

**Comment by e-alfred** [comment] 2018-03-05 11:23
This is a duplicate of https://github.com/e-alfred/flowupload/issues/15 and also https://github.com/e-alfred/flowupload/issues/7. Please add the issue there.

**Closed by e-alfred** 2018-03-05 11:23 UTC
Labels: bug, duplicate
