### ISSUE TITLE
Support UTF-8

### ISSUE THREAD

**Issue by Creling** [e-alfred/flowupload#54] opened 2019-04-12 15:59 UTC
### Steps to reproduce
1. rename a file to no-ascii charactors like Chinese
2. upload it via flowupload
3. you will get a file with empty name 

### Expected behaviour
Hoping flowupload can remain the file name while uploading

### Actual behaviour

the file name is empty

### Server configuration

**Operating system**: Centos7

**Web server:** Nginx

**Database:** Mysql

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page)  Nextcloud 15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**  fresh install

**Where did you install Nextcloud from:** Docker

**Comment by e-alfred** [comment] 2019-04-12 16:41
This is a duplicate of https://github.com/e-alfred/flowupload/issues/7 and should be fixed by https://github.com/e-alfred/flowupload/pull/47 in version 0.1.0.

**Closed by e-alfred** 2019-04-12 16:41 UTC
Labels: duplicate
