### ISSUE TITLE
NextCloud freezes after upload

### ISSUE THREAD

**Issue by Zegorax** [e-alfred/flowupload#56] opened 2019-04-28 14:55 UTC
### Steps to reproduce
1. Install FlowUpload app
2. Upload a big file (I tested with 700MB and 6GB files, but it happens with small files as well)
3. Wait for the upload to progress
4. Once the upload bar reaches the end, there's no upload confirmation. NextCloud then freezes for all users and is not responsive. I think it is frozen the time needed to process the file.

### Expected behaviour
NextCloud should not freeze.

### Actual behaviour
NextCloud freezes for all users.

### Server configuration

**Operating system**:
Ubuntu 18.04.2 LTS

**Web server:**
Apache2

**Database:**
MySQL in Docker

**PHP version:**
PHP 7.2.17-0ubuntu0.18.04.1

**Nextcloud version:** (see Nextcloud admin page)
15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**
NextCloud was installed with older version

**Where did you install Nextcloud from:**
Bare-metal from Nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - announcementcenter: 3.4.1
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_downloadactivity: 1.4.0
  - files_fulltextsearch: 1.2.6
  - files_pdfviewer: 1.4.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - flowupload: 0.1.0
  - fulltextsearch: 1.2.5
  - gallery: 18.2.0
  - groupfolders: 2.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - music: 0.9.4
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - onlyoffice: 2.1.6
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - ransomware_protection: 1.3.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - sharerenamer: 2.6.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - unsplash: 1.1.3
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - files_external
  - ransomware_detection
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "filelocking.enabled": false,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** 
LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+--------------------------------------------------------------+
| Configuration                 | s01                                                          |
+-------------------------------+--------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                            |
| homeFolderNamingRule          |                                                              |
| lastJpegPhotoLookup           | 0                                                            |
| ldapAgentName                 |                                                              |
| ldapAgentPassword             | ***                                                          |
| ldapAttributesForGroupSearch  |                                                              |
| ldapAttributesForUserSearch   |                                                              |
| ldapBackupHost                |                                                              |
| ldapBackupPort                |                                                              |
| ldapBase                      | dc=foo,dc=bar                                             |
| ldapBaseGroups                | dc=Groups,dc=foo,dc=bar                                   |
| ldapBaseUsers                 | dc=Users,dc=foo,dc=bar                                    |
| ldapCacheTTL                  | 600                                                          |
| ldapConfigurationActive       | 1                                                            |
| ldapDefaultPPolicyDN          |                                                              |
| ldapDynamicGroupMemberURL     |                                                              |
| ldapEmailAttribute            | mail                                                         |
| ldapExperiencedAdmin          | 0                                                            |
| ldapExpertUUIDGroupAttr       |                                                              |
| ldapExpertUUIDUserAttr        | uid                                                          |
| ldapExpertUsernameAttr        |                                                              |
| ldapGidNumber                 | gidNumber                                                    |
| ldapGroupDisplayName          | cn                                                           |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))                               |
| ldapGroupFilterGroups         |                                                              |
| ldapGroupFilterMode           | 0                                                            |
| ldapGroupFilterObjectclass    | posixGroup                                                   |
| ldapGroupMemberAssocAttr      | memberUid                                                    |
| ldapHost                      | 127.0.0.1                                                    |
| ldapIgnoreNamingRules         |                                                              |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mail=%uid)))) |
| ldapLoginFilterAttributes     | mail                                                         |
| ldapLoginFilterEmail          | 0                                                            |
| ldapLoginFilterMode           | 0                                                            |
| ldapLoginFilterUsername       | 1                                                            |
| ldapNestedGroups              | 0                                                            |
| ldapOverrideMainServer        |                                                              |
| ldapPagingSize                | 500                                                          |
| ldapPort                      | 389                                                          |
| ldapQuotaAttribute            |                                                              |
| ldapQuotaDefault              |                                                              |
| ldapTLS                       | 0                                                            |
| ldapUserAvatarRule            | default                                                      |
| ldapUserDisplayName           | cn                                                           |
| ldapUserDisplayName2          |                                                              |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                               |
| ldapUserFilterGroups          |                                                              |
| ldapUserFilterMode            | 0                                                            |
| ldapUserFilterObjectclass     | inetOrgPerson                                                |
| ldapUuidGroupAttribute        | auto                                                         |
| ldapUuidUserAttribute         | auto                                                         |
| turnOffCertCheck              | 0                                                            |
| turnOnPasswordChange          | 0                                                            |
| useMemberOfToDetectMembership | 1                                                            |
+-------------------------------+--------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:**
Tested with Firefox and Safari

**Operating system:**
MacOS 10.14.4

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing is logged during the issue
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing is logged during the issue
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (flowupload, line 0)
```
</details>

**Comment by e-alfred** [comment] 2019-05-17 18:55
The problem seems to be that somehow the file isn't getting moved to the final directory correctly from the temp directory. Can you confirm that the file is uploaded to the temporary Flowupload in the data folder of your user? The folder is called `/.flowupload_tmp/`.

**Comment by TessyPowder** [comment] 2019-07-27 08:30
Could you please log the cpu and drive usage during the unresponsive time and post it here ?
My guess is that your Server isn't fast enough or your drive(s) are to busy assembling the chunks into the final File and then the Server gets unresponsive. What Hardware is inside your Server ? Is your Nextcloud Webserver inside a docker ?

**Comment by dimm0** [comment] 2019-12-10 22:15
Same here
Server has enough power (CPU usage actually dropped), but storage is relatively slow (cephFS)

**Comment by e-alfred** [comment] 2020-05-28 10:28
Is this issue still relevant with Flowupload 1.0? @dimm0 @Zegorax can you reproduce this error with our new release?

**Comment by dimm0** [comment] 2020-06-08 23:16
Seems to work great now. And I love the new target choose dialog
Thanks!

**Comment by TessyPowder** [comment] 2020-06-09 05:58
> Seems to work great now. And I love the new target choose dialog
> Thanks!

Cool. I am going to close this issue now 👍

**Closed by TessyPowder** 2020-06-09 05:58 UTC
Labels: help wanted
