### ISSUE TITLE
Folder Upload doesn't preserve File Modification Dates

### ISSUE THREAD

**Issue by macbrayne** [e-alfred/flowupload#80] opened 2020-04-14 21:44 UTC
### Steps to reproduce
1. Select a folder containing old files in flowupload
2. Inspect the resulting files' 'modified' attributes

### Expected behaviour
The files preserve their old timestamp like the default upload tool. The upload time is already stored seperately in the db so this shouldn't introduce any problems.

### Actual behaviour
Instead the attribute is set to the upload time.

## Server configuration detail

**Operating system:** Linux 4.19.107-Unraid #1 SMP Thu Mar 5 13:55:57 PST 2020 x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.4.12

**PHP version:** 

7.3.16
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 18.0.3 - 18.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Installed 20 days ago

**Where did you install Nextcloud from:** nextcloud:latest

<details><summary>Signing status</summary>

No errors have been found.

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - bookmarks: 2.3.4
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - dav: 1.14.0
 - documentserver_community: 0.1.5
 - event_update_notification: 1.0.1
 - extract: 1.2.3
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_lock: 0.8.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - flowupload: 0.1.8
 - impersonate: 1.5.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.4
 - metadata: 0.11.1
 - nextcloud_announcements: 1.7.0
 - notes: 3.2.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - occweb: 0.0.7
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - polls: 1.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.7
 - support: 1.1.0
 - survey_client: 1.6.0
 - suspicious_login: 3.1.0
 - systemtags: 1.8.0
 - talk_simple_poll: 1.1.0
 - tasks: 0.12.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_totp: 4.1.3
 - twofactor_u2f: 5.1.0
 - twofactor_webauthn: 0.2.4
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.example.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.3.0",
    "overwrite.cli.url": "https:\/\/nextcloud.example.de",
    "overwritehost": "nextcloud.example.de",
    "overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "family",
        "admin"
    ],
    "twofactor_enforced_excluded_groups": []
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** None

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/81.0.4044.92 Chrome/81.0.4044.92 Safari/537.36

**Operating system:** Kubuntu 19.04

**Comment by TessyPowder** [comment] 2020-04-14 21:49
Duplicate of #75 , but thanks for the detailed issue description 😃

**Comment by macbrayne** [comment] 2020-04-14 21:50
Relevant server issue: https://github.com/nextcloud/server/issues/14982

**Comment by macbrayne** [comment] 2020-04-14 21:53
> Duplicate of #75 , but thanks for the detailed issue description 😃

#75 is labeled as feature request although most users won't expect the current behaviour.

**Comment by TessyPowder** [comment] 2020-04-15 07:03
Ok. Preserving the modification date by default makes sense, but like in #75 the user should be able to activate/deactivate this behaviour.

**Comment by e-alfred** [comment] 2020-05-14 17:06
We should keep the discussion in one place, so please add any further comments to https://github.com/e-alfred/flowupload/issues/75. As said above, the user should choose whether the original date or the upload date should be kept because sometimes the former is not desired (like uploading a file with an original date from 10 years ago not showing up at the top if "sort by date" is selected.

**Closed by e-alfred** 2020-05-14 17:06 UTC
Labels: duplicate
