### ISSUE TITLE
Does Flow Upload support S3?

### ISSUE THREAD

**Issue by samsonle1809** [e-alfred/flowupload#43] opened 2019-01-03 09:46 UTC
I have a Nextcloud instance using S3 as primary storage. I upload some files via Flow Upload but request upload not complete. Flow Upload show button "Retry" and I see upload.php return 500 Internal Server Error. This is Nextcloud log: "message":"mkdir(): No such file or directory at \/var\/www\/html\/custom_apps\/flowupload\/ajax\/upload.php#37".

Does Flow Upload support S3?

**Comment by e-alfred** [comment] 2019-01-25 23:17
S3 is an external storage which is not yet supported by Flowupload.

**Comment by e-alfred** [comment] 2019-10-27 15:31
Duplicate of https://github.com/e-alfred/flowupload/issues/46.

**Closed by e-alfred** 2019-10-27 15:31 UTC
Labels: enhancement

**Comment by bsommerhalder** [comment] 2020-01-11 10:39
Hi there @e-alfred , this is not a duplicate of #46 in that the original poster @samsonle1809 has S3 set as primary storage (not added as an external storage). Might this change the nature of the issue/solution? I am in the same situation. Thanks in advance.

**Comment by TessyPowder** [comment] 2020-01-11 10:58
> Might this change the nature of the issue/solution?

no (99.9% sure)

But once my PR #73 gets merged uploading to S3 (both external storage and primary storage) should work
